apiVersion: apps/v1
kind: deploymemt
metadata:
  name: db-deployment
  labels:
    app: db-dep
    use: middleware
spec:
  template:
   metadata: 
    name: postgres-pod
    labels:
     app: postgres-pod
     use: voting
   spec:
    containers:
    - name: postgres-app-pod
      image: postgres:9.4
      ports:
      - containerPort: 5432
  replicas: 1
  selector:
    matchLabels:
      app: postgres-pod
