apiVersion: v1
kind: Pod
metadata:
  name: resulti-pod
  labels:
    app: result-pod
    use: voting
spec:
  containers:
  - name: result-app-pod
    image: dockersamples/examplevotingapp_result
    ports:
    - containerPort: 80
