apiVersion: apps/v1
kind: deploymemt
metadata:
  name: voting-deployment
  labels:
    app: voting-dep
    use: front
spec:
  template:
   metadata:
    name: voting-pod
    labels:
     app: voting-pod
     use: voting
   spec:
    containers:
    - name: voting-app-pod
      image: dockersamples/examplevotingapp_vote
      ports:
      - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      app: voting-pod
